### ISSUE TITLE
keepMarkdownSyntaxFromTitle and hyphenToSpace conflict

### ISSUE THREAD

**Issue by jasonkuhrt** [jooy2/vitepress-sidebar#176]
Here is an example where using `hyphenToSpace` breaks the HTML from `keepMarkdownSyntaxFromTitle`

![CleanShot 2024-09-13 at 14 16 32@2x](https://github.com/user-attachments/assets/fea16f30-c2ee-4a06-bf1e-88eaa0531857)

**Comment by jooy2** [comment]
Hello! Thank you for using `vitepress-sidebar` and reporting the issue.

This issue was resolved in release version `1.25.4`.

I fixed it to not perform any formatting on the Markdown syntax or attribute text within HTML tags. Could you please upgrade to that version and see if it meets your requirements?

If the issue no longer occurs, i'll close the issue.

Regards,

**Comment by jasonkuhrt** [comment]
@jooy2 Thanks, working great!

**Comment by jasonkuhrt** [comment]
Hm, I think I mis-reported my findings. The issue remains. I think I hadn't correctly refreshed the Vitepress preview. This is what I see now:

![CleanShot 2024-09-16 at 22 29 13@2x](https://github.com/user-attachments/assets/851d7ce6-0d53-4def-93df-9a86bbcd1e31)

**Comment by jooy2** [comment]
Hello,

Hmm... that's odd, I've been testing with your repository (referenced in the following link: https://github.com/jooy2/vitepress-sidebar/network/dependents) and it doesn't seem to reproduce the issue for me. (I added the `hyphenToSpace` option in the config file)

![SCR-20240917-qtrd-2](https://github.com/user-attachments/assets/9b949471-0695-43ea-b822-32c0ede7dee5)

It looks like your code also removes the hypen symbols in a function called `fixTitles`, could you check if temporarily disabling this function causes the same issue?

Also, this didn't seem to cause the problem when I tried it, so it could be an issue with `pnpm` or VitePress' build cache. Can you confirm that you have the latest version of `vitepress-sidebar` installed correctly and that this is a fresh build?

Regards,

**Comment by jooy2** [comment]
Hello!

Can you let me know if this issue has been resolved recently? If there is no response, i will consider it resolved and close the issue.
If you continue to experience the issue, please feel free to leave a reply.

Regards,

**Comment by jasonkuhrt** [comment]
Hey @jooy2 it seems to be fine now. I don't use HTML in the titles anymore but as well I trust your reporting too that maybe I hit an issue with local cache etc. Thanks!

**Comment by jooy2** [comment]
Thanks for letting me know, and feel free to open a new issue if you run into any new problems :)
